# Generated by Django 3.0.2 on 2020-01-19 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of a category', max_length=200, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Short description of the expense', max_length=200, verbose_name='Description')),
                ('shop', models.CharField(help_text='Shop name', max_length=200, verbose_name='Shop')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Purchase / income date', verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Purchase / income amount', max_digits=12, verbose_name='Amount')),
                ('category', models.ForeignKey(help_text='', on_delete=django.db.models.deletion.PROTECT, to='expenses.Category', verbose_name='Category')),
            ],
        ),
    ]
