# Generated by Django 3.0.2 on 2020-01-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='expense',
            name='income',
            field=models.BooleanField(blank=True, default=False, help_text="If not income, then it's an expense", verbose_name='Is this income?'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.PROTECT, to='expenses.Category', verbose_name='Category'),
        ),
    ]
