# Generated by Django 3.0.2 on 2020-02-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200129_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.PROTECT, to='expenses.Category', verbose_name='Category'),
        ),
    ]
